### ISSUE TITLE
in_reply_to must be given

### ISSUE THREAD

**Issue by HackyPenguin** [RaphYot/err-jira#3]
Hi guys, 

I have a slight issue when running this with a rocketchat backend.  it seems whenever self.send is called it returns Argument `in_reply_to` must be given.

As far as I understand it this is passed here: 
   

```

self.send(msg.frm,
                      'Ticket must be passed',
                      message_type=msg.type,
                      in_reply_to=msg,
                      groupchat_nick_reply=True)
            return False  



```

the message variable is defined by errbot itself if I am correct a quick read of the errbot documentation seems to point at in_reply_to being optional however when commented out it still repeats the same error. 

I am new to errbot and pointers here would be great.

**Comment by rawouter** [comment]
I don't have any Jira instance to run that bot anymore, I'm not sure where this is coming from.
Looking at the code I believe the only line where we could call the send function is from send_card:
https://github.com/rawouter/err-jira/blob/master/errjira.py#L185

But in_reply_to is set there. Do you have a stack trace maybe?
Are you sure this is coming from this plugin?

**Comment by HackyPenguin** [comment]
Actually on second look ( amazing what a fresh pair of eyes can do) looks like this issue is caused by the rocketchat backend ill close this for now. Cheers
